/*
 * PackJacket - GUI frontend to IzPack to make Java-based installers
 * Copyright (C) 2008 - 2009  Amandeep Grewal, Manodasan Wignarajah
 *
 * PackJacket is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PackJacket is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PackJacket.  If not, see <http://www.gnu.org/licenses/>.
 */
package packjacket.gui.packs;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Arrays;
import javax.swing.JOptionPane;
import packjacket.RunnerClass;
import packjacket.gui.ArrayListModel;
import packjacket.gui.GUIUtils;
import packjacket.gui.OSPanel;
import packjacket.xml.Executable;
import packjacket.xml.Pack;
import packjacket.xml.Parsable;

/**
 * The optional packs panel
 * @author Amandeep Grewal
 */
public class GeneralOptionalPanel extends javax.swing.JPanel {

    public ArrayListModel<Executable> executables;
    public ArrayListModel<Parsable> parsables;
    public ArrayListModel<String> depends;
    public boolean isEditing;

    /** Creates new form GeneralOptional */
    public GeneralOptionalPanel() {
        initComponents();
        executables = new ArrayListModel<Executable>(execsList);
        parsables = new ArrayListModel<Parsable>(parsablesList);
        depends = new ArrayListModel<String>(dependsList);
        parent.addItem("");
        for (Pack p : RunnerClass.mf.packsPanel.packs.list) {
            dependsChoices.addItem(p.toString());
            parent.addItem(p.toString());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        screenshot = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        parent = new javax.swing.JComboBox();
        osPanel = new javax.swing.JPanel();
        jPanel23 = new javax.swing.JPanel();
        jScrollPane24 = new javax.swing.JScrollPane();
        dependsList = new javax.swing.JList();
        addBtn21 = new javax.swing.JButton();
        deleteBtn21 = new javax.swing.JButton();
        dependsChoices = new javax.swing.JComboBox();
        jPanel24 = new javax.swing.JPanel();
        jScrollPane25 = new javax.swing.JScrollPane();
        parsablesList = new javax.swing.JList();
        addBtn22 = new javax.swing.JButton();
        editBtn22 = new javax.swing.JButton();
        deleteBtn22 = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jScrollPane26 = new javax.swing.JScrollPane();
        execsList = new javax.swing.JList();
        addBtn23 = new javax.swing.JButton();
        editBtn23 = new javax.swing.JButton();
        deleteBtn23 = new javax.swing.JButton();
        hidden = new javax.swing.JCheckBox();
        loose = new javax.swing.JCheckBox();

        jLabel1.setText("Pack Screenshot");

        screenshot.setBackground(new java.awt.Color(254, 254, 254));
        screenshot.setEditable(false);

        jButton1.setText("Browse");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Parent Pack");

        javax.swing.GroupLayout osPanelLayout = new javax.swing.GroupLayout(osPanel);
        osPanel.setLayout(osPanelLayout);
        osPanelLayout.setHorizontalGroup(
            osPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 127, Short.MAX_VALUE)
        );
        osPanelLayout.setVerticalGroup(
            osPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 86, Short.MAX_VALUE)
        );

        osPanel = new OSPanel();

        jPanel23.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 213, 213), 1, true), "Depends", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jScrollPane24.setViewportView(dependsList);

        addBtn21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        addBtn21.setToolTipText("Add");
        addBtn21.setPreferredSize(new java.awt.Dimension(35, 25));
        addBtn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn21ActionPerformed(evt);
            }
        });

        deleteBtn21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
        deleteBtn21.setToolTipText("Delete");
        deleteBtn21.setPreferredSize(new java.awt.Dimension(35, 25));
        deleteBtn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn21ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addComponent(addBtn21, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn21, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
            .addComponent(dependsChoices, 0, 134, Short.MAX_VALUE)
            .addComponent(jScrollPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addComponent(dependsChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(deleteBtn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane24, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
        );

        jPanel24.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 213, 213), 1, true), "Parsables", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jScrollPane25.setViewportView(parsablesList);

        addBtn22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        addBtn22.setToolTipText("Add");
        addBtn22.setPreferredSize(new java.awt.Dimension(35, 25));
        addBtn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn22ActionPerformed(evt);
            }
        });

        editBtn22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        editBtn22.setToolTipText("Edit");
        editBtn22.setPreferredSize(new java.awt.Dimension(35, 25));
        editBtn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn22ActionPerformed(evt);
            }
        });

        deleteBtn22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
        deleteBtn22.setToolTipText("Delete");
        deleteBtn22.setPreferredSize(new java.awt.Dimension(35, 25));
        deleteBtn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addComponent(addBtn22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn22, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE))
            .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane25, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
        );

        jPanel25.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(213, 213, 213), 1, true), "Executables", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jScrollPane26.setViewportView(execsList);

        addBtn23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        addBtn23.setToolTipText("Add");
        addBtn23.setPreferredSize(new java.awt.Dimension(35, 25));
        addBtn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtn23ActionPerformed(evt);
            }
        });

        editBtn23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        editBtn23.setToolTipText("Edit");
        editBtn23.setPreferredSize(new java.awt.Dimension(35, 25));
        editBtn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtn23ActionPerformed(evt);
            }
        });

        deleteBtn23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
        deleteBtn23.setToolTipText("Delete");
        deleteBtn23.setPreferredSize(new java.awt.Dimension(35, 25));
        deleteBtn23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtn23ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel25Layout = new javax.swing.GroupLayout(jPanel25);
        jPanel25.setLayout(jPanel25Layout);
        jPanel25Layout.setHorizontalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel25Layout.createSequentialGroup()
                .addComponent(addBtn23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editBtn23, javax.swing.GroupLayout.PREFERRED_SIZE, 40, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deleteBtn23, javax.swing.GroupLayout.PREFERRED_SIZE, 39, Short.MAX_VALUE))
            .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );
        jPanel25Layout.setVerticalGroup(
            jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel25Layout.createSequentialGroup()
                .addGroup(jPanel25Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBtn23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane26, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE))
        );

        hidden.setText("Hidden");
        hidden.setToolTipText("Whether this pack is hidden in the pack's selection panel in the installer");

        loose.setText("Loose");
        loose.setToolTipText("Whether the files for this pack will not be included with the installer");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jPanel25, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(loose)
                            .addComponent(osPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(hidden, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(screenshot, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(screenshot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(parent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel25, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel24, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(osPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hidden)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loose)
                        .addGap(24, 24, 24)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBtn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn23ActionPerformed
        isEditing = false;
        ExecutablePanel execPanel = new ExecutablePanel();
        ExecutableOptionalPanel execOp = new ExecutableOptionalPanel();
        makePanel(execPanel, execOp);
    }//GEN-LAST:event_addBtn23ActionPerformed

    private void makePanel(final ExecutablePanel execPanel, final ExecutableOptionalPanel execOp) {
        RunnerClass.mf.addP(GUIUtils.makeCollapserPanel(execPanel, execOp,
                new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {
                        Executable exec;
                        if (isEditing)
                            exec = executables.getElement();
                        else
                            exec = new Executable();

                        StringBuffer errormsg = new StringBuffer();
                        if (execPanel.targetFileExec.getSelectedItem().toString().trim().equals(""))
                            errormsg.append("You have not specified a file to execute.\n");
                        if (execPanel.targetFileExec.getSelectedItem().toString().trim().toLowerCase().endsWith(".jar"))
                            if (execPanel.clas.getText().trim().equals(""))
                                errormsg.append("You have specified a JAR file, but not a main class.\n");
                        errormsg.append(((OSPanel) osPanel).getError());
                        if (errormsg.length() != 0) {
                            String msg = errormsg.substring(0, errormsg.length() - 1);
                            JOptionPane.showMessageDialog(RunnerClass.mf, msg, "Incomplete Data", JOptionPane.ERROR_MESSAGE);
                            return;
                        }


                        exec.targetfile = execPanel.targetFileExec.getSelectedItem().toString();
                        exec.clas = execPanel.clas.getText().trim();
                        exec.stage = execPanel.stageCombo.getSelectedItem().toString();
                        exec.failure = execPanel.failureCombo.getSelectedItem().toString();
                        exec.os = ((OSPanel) execOp.osPanel).getOS();
                        exec.keep = execPanel.keepOption.isSelected();
                        exec.args = Arrays.asList(execOp.arguments.getText().split("\n"));

                        if (!isEditing)
                            executables.add(exec);


                        RunnerClass.mf.removeP();
                    }
                },
                new ActionListener() {

                    @Override
                    public void actionPerformed(ActionEvent e) {

                        RunnerClass.mf.removeP();
                    }
                }));
    }

    private void editBtn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn23ActionPerformed
        isEditing = true;
        ExecutablePanel execPanel = new ExecutablePanel();
        ExecutableOptionalPanel execOp = new ExecutableOptionalPanel();
        Executable exec = executables.getElement();

        execPanel.targetFileExec.setSelectedItem(exec.targetfile);
        execPanel.clas.setText(exec.clas);
        execPanel.stageCombo.setSelectedItem(exec.stage);
        execPanel.failureCombo.setSelectedItem(exec.failure);
        ((OSPanel) execOp.osPanel).setOS(exec.os);
        execPanel.keepOption.setSelected(exec.keep);
        for (String s : exec.args)
            execOp.arguments.append(s + "\n");
        makePanel(execPanel, execOp);
    }//GEN-LAST:event_editBtn23ActionPerformed

    private void deleteBtn23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn23ActionPerformed
        executables.remove();
    }//GEN-LAST:event_deleteBtn23ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        GUIUtils.open("images", screenshot);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addBtn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn22ActionPerformed
        RunnerClass.mf.addP(new ParsablePanel(parsables));
    }//GEN-LAST:event_addBtn22ActionPerformed

    private void editBtn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtn22ActionPerformed
        try {
            RunnerClass.mf.addP(new ParsablePanel(parsables, parsablesList.getSelectedIndex()));
        } catch (java.lang.ArrayIndexOutOfBoundsException e) {
        }
    }//GEN-LAST:event_editBtn22ActionPerformed

    private void deleteBtn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn22ActionPerformed
        parsables.remove();
    }//GEN-LAST:event_deleteBtn22ActionPerformed

    private void addBtn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtn21ActionPerformed
        if (depends.list.contains(dependsChoices.getSelectedItem().toString())) {
            JOptionPane.showMessageDialog(RunnerClass.mf, "You have already added that pack!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        depends.add(dependsChoices.getSelectedItem().toString());
    }//GEN-LAST:event_addBtn21ActionPerformed

    private void deleteBtn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtn21ActionPerformed
        depends.remove();
    }//GEN-LAST:event_deleteBtn21ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addBtn21;
    public javax.swing.JButton addBtn22;
    public javax.swing.JButton addBtn23;
    public javax.swing.JButton deleteBtn21;
    public javax.swing.JButton deleteBtn22;
    public javax.swing.JButton deleteBtn23;
    public javax.swing.JComboBox dependsChoices;
    public javax.swing.JList dependsList;
    public javax.swing.JButton editBtn22;
    public javax.swing.JButton editBtn23;
    public javax.swing.JList execsList;
    public javax.swing.JCheckBox hidden;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel23;
    public javax.swing.JPanel jPanel24;
    public javax.swing.JPanel jPanel25;
    public javax.swing.JScrollPane jScrollPane24;
    public javax.swing.JScrollPane jScrollPane25;
    public javax.swing.JScrollPane jScrollPane26;
    public javax.swing.JCheckBox loose;
    public javax.swing.JPanel osPanel;
    public javax.swing.JComboBox parent;
    public javax.swing.JList parsablesList;
    public javax.swing.JTextField screenshot;
    // End of variables declaration//GEN-END:variables
}
