/*
 * PackJacket - GUI frontend to IzPack to make Java-based installers
 * Copyright (C) 2008 - 2009  Amandeep Grewal, Manodasan Wignarajah
 *
 * PackJacket is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PackJacket is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PackJacket.  If not, see <http://www.gnu.org/licenses/>.
 */
package packjacket.gui.userinput;

import packjacket.gui.BtnPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.WindowConstants;
import packjacket.RunnerClass;

/**
 * The panel for Choice
 * @author Manodasan Wignarajah
 */
public class ChoicePanel extends javax.swing.JPanel {

    /** Creates new form ChoicePanel */
    public ChoicePanel(String type) {
        initComponents();
        //Sets the appropriate fields as visible and not visible
        if (type.equals("check")) {
            variableLabel.setVisible(true);
            variable.setVisible(true);
            iffalse.setVisible(true);
            ifFalseLabel.setVisible(true);
            preselected.setVisible(true);
        } else {
            variableLabel.setVisible(false);
            variable.setVisible(false);
            iffalse.setVisible(false);
            ifFalseLabel.setVisible(false);
            preselected.setVisible(false);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        textLabel = new javax.swing.JLabel();
        variableLabel = new javax.swing.JLabel();
        iftrueLabel = new javax.swing.JLabel();
        ifFalseLabel = new javax.swing.JLabel();
        preselected = new javax.swing.JCheckBox();
        text = new javax.swing.JTextField();
        variable = new javax.swing.JTextField();
        iftrue = new javax.swing.JTextField();
        iffalse = new javax.swing.JTextField();
        okPanel = new javax.swing.JPanel();

        jButton2.setText("jButton2");

        textLabel.setText("Text");

        variableLabel.setText("Variable");

        iftrueLabel.setText("Value if Selected");

        ifFalseLabel.setText("Value if not Selected");

        preselected.setText("Pre-Selected");

        javax.swing.GroupLayout okPanelLayout = new javax.swing.GroupLayout(okPanel);
        okPanel.setLayout(okPanelLayout);
        okPanelLayout.setHorizontalGroup(
            okPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 220, Short.MAX_VALUE)
        );
        okPanelLayout.setVerticalGroup(
            okPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        okPanel = new BtnPanel(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                RunnerClass.mf.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
                RunnerClass.mf.removeP();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textLabel)
                    .addComponent(variableLabel)
                    .addComponent(iftrueLabel)
                    .addComponent(ifFalseLabel)
                    .addComponent(preselected))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(variable, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(iftrue, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                    .addComponent(iffalse, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(okPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textLabel)
                    .addComponent(text, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(variableLabel)
                    .addComponent(variable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iftrueLabel)
                    .addComponent(iftrue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ifFalseLabel)
                    .addComponent(iffalse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(preselected)
                .addGap(5, 5, 5)
                .addComponent(okPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ifFalseLabel;
    public javax.swing.JTextField iffalse;
    public javax.swing.JTextField iftrue;
    private javax.swing.JLabel iftrueLabel;
    private javax.swing.JButton jButton2;
    public javax.swing.JPanel okPanel;
    public javax.swing.JCheckBox preselected;
    public javax.swing.JTextField text;
    private javax.swing.JLabel textLabel;
    public javax.swing.JTextField variable;
    private javax.swing.JLabel variableLabel;
    // End of variables declaration//GEN-END:variables
}
