/*
 * PackJacket - GUI frontend to IzPack to make Java-based installers
 * Copyright (C) 2008 - 2009  Amandeep Grewal, Manodasan Wignarajah
 *
 * PackJacket is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PackJacket is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PackJacket.  If not, see <http://www.gnu.org/licenses/>.
 */
package packjacket.gui.userinput;

import packjacket.gui.BtnPanel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import packjacket.RunnerClass;
import packjacket.gui.ArrayListModel;
import packjacket.xml.Choice;

/**
 * The panel for List Choice
 * @author Manodasan Wignarajah
 */
public class ListChoicePanel extends javax.swing.JPanel {

    public ArrayListModel<Choice> choices;
    public ArrayListModel<Choice> choices2;
    public boolean isEditing;

    /** Creates new form ListChoicePanel */
    public ListChoicePanel() {
        initComponents();
        choices = new ArrayListModel(choicesList);
        choices2 = new ArrayListModel(choicesList2);
        isEditing = false;
        radioButtonActionPerformed(null);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        radioButton = new javax.swing.JRadioButton();
        comboBox = new javax.swing.JRadioButton();
        checkBox = new javax.swing.JRadioButton();
        descriptionOption = new javax.swing.JCheckBox();
        descriptionPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        align = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        comboBoxLabel = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        add = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        remove = new javax.swing.JButton();
        up = new javax.swing.JButton();
        down = new javax.swing.JButton();
        choiceListPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        choicesList = new javax.swing.JList();
        choiceListPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        choicesList2 = new javax.swing.JList();
        okPanel3 = new javax.swing.JPanel();
        variablePanel = new javax.swing.JPanel();
        variable = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        preselected = new javax.swing.JComboBox();

        buttonGroup1.add(radioButton);
        radioButton.setText("Radio Buttons");
        radioButton.setSelected(true);
        radioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonActionPerformed(evt);
            }
        });

        buttonGroup1.add(comboBox);
        comboBox.setText("Combo Box");
        comboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboBoxActionPerformed(evt);
            }
        });

        buttonGroup1.add(checkBox);
        checkBox.setText("Check Boxes");
        checkBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBoxActionPerformed(evt);
            }
        });

        descriptionOption.setText("Specify Description");
        descriptionOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionOptionActionPerformed(evt);
            }
        });

        descriptionPanel.setVisible(false);

        jLabel3.setText("Align");

        jLabel4.setText("Description");

        align.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Left", "Centre", "Right" }));

        javax.swing.GroupLayout descriptionPanelLayout = new javax.swing.GroupLayout(descriptionPanel);
        descriptionPanel.setLayout(descriptionPanelLayout);
        descriptionPanelLayout.setHorizontalGroup(
            descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(47, 47, 47)
                .addGroup(descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(description, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                    .addComponent(align, 0, 288, Short.MAX_VALUE)))
        );
        descriptionPanelLayout.setVerticalGroup(
            descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(descriptionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(description, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(descriptionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(align, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setText("Combo Box Label");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Choices"));

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
        remove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeActionPerformed(evt);
            }
        });

        up.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/up.png"))); // NOI18N
        up.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upActionPerformed(evt);
            }
        });

        down.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/down.png"))); // NOI18N
        down.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(choicesList);

        javax.swing.GroupLayout choiceListPanel1Layout = new javax.swing.GroupLayout(choiceListPanel1);
        choiceListPanel1.setLayout(choiceListPanel1Layout);
        choiceListPanel1Layout.setHorizontalGroup(
            choiceListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );
        choiceListPanel1Layout.setVerticalGroup(
            choiceListPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
        );

        choiceListPanel2.setVisible(false);

        jScrollPane2.setViewportView(choicesList2);

        javax.swing.GroupLayout choiceListPanel2Layout = new javax.swing.GroupLayout(choiceListPanel2);
        choiceListPanel2.setLayout(choiceListPanel2Layout);
        choiceListPanel2Layout.setHorizontalGroup(
            choiceListPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );
        choiceListPanel2Layout.setVerticalGroup(
            choiceListPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 156, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(choiceListPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(choiceListPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(add, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edit, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(remove, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(up, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(down, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(edit, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(remove, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(up, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(down, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(choiceListPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(choiceListPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout okPanel3Layout = new javax.swing.GroupLayout(okPanel3);
        okPanel3.setLayout(okPanel3Layout);
        okPanel3Layout.setHorizontalGroup(
            okPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 312, Short.MAX_VALUE)
        );
        okPanel3Layout.setVerticalGroup(
            okPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );

        okPanel3 = new BtnPanel(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                
                RunnerClass.mf.removeP();
            }
        });

        jLabel1.setText("Variable");

        jLabel2.setText("Pre-Selected");

        javax.swing.GroupLayout variablePanelLayout = new javax.swing.GroupLayout(variablePanel);
        variablePanel.setLayout(variablePanelLayout);
        variablePanelLayout.setHorizontalGroup(
            variablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(variablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(variablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(40, 40, 40)
                .addGroup(variablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(variable, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                    .addComponent(preselected, 0, 287, Short.MAX_VALUE)))
        );
        variablePanelLayout.setVerticalGroup(
            variablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(variablePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(variablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(variable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(variablePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preselected, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(okPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(radioButton)
                        .addGap(18, 18, 18)
                        .addComponent(comboBox)
                        .addGap(18, 18, 18)
                        .addComponent(checkBox))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(descriptionOption))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(descriptionPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 302, Short.MAX_VALUE))
                    .addComponent(variablePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButton)
                    .addComponent(comboBox)
                    .addComponent(checkBox))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(variablePanel, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionOption)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriptionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(comboBoxLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Adjusts the GUI
     */
    public void adjustUI() {
        descriptionOptionActionPerformed(null);
        actionPerformed();
    }

    private void descriptionOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionOptionActionPerformed
        //Performs appropriate action if description is selected
        descriptionPanel.setVisible(descriptionOption.isSelected());
        RunnerClass.mf.pack();
}//GEN-LAST:event_descriptionOptionActionPerformed

    private void actionPerformed() {
        //Sets the gui fields as visible or not
        variablePanel.setVisible(radioButton.isSelected() || comboBox.isSelected());
        comboBoxLabel.setVisible(comboBox.isSelected());
        jLabel5.setVisible(comboBox.isSelected());
        choiceListPanel2.setVisible(checkBox.isSelected());
        choiceListPanel1.setVisible(!checkBox.isSelected());
        updateUI();
        RunnerClass.mf.pack();
    }
//The following methods call the actionPerformed method to adjust the fields depending on what is chosen
    private void radioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonActionPerformed
        actionPerformed();
    }//GEN-LAST:event_radioButtonActionPerformed

    private void comboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboBoxActionPerformed
        actionPerformed();
    }//GEN-LAST:event_comboBoxActionPerformed

    private void checkBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBoxActionPerformed
        actionPerformed();
    }//GEN-LAST:event_checkBoxActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        //Adds a choice
        String type = "";
        if (comboBox.isSelected())
            type = "combo";
        else if (checkBox.isSelected())
            type = "check";
        else
            type = "radio";
        final ChoicePanel choicePanel = new ChoicePanel(type);
        if (evt != null)
            isEditing = false;
        else {
            Choice c;
            //Gets the element from the appropriate JList
            if (choiceListPanel1.isVisible())
                c = (Choice) choices.getElement();
            else
                c = (Choice) choices2.getElement();
            choicePanel.text.setText(c.text);
            //Sets the values on the fields
            if (choicePanel.variable.isVisible()) {
                choicePanel.variable.setText(c.variable);
                choicePanel.iftrue.setText(c.trueIf);
                choicePanel.iffalse.setText(c.falseIf);
                choicePanel.preselected.setSelected(c.set);
            } else
                choicePanel.iftrue.setText(c.value);

        }
        //adds Action Listener for the ok button
        ((BtnPanel) choicePanel.okPanel).addOkBtnActionListener(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                //Looks for errors and shows the Error messages
                StringBuffer errormsg = new StringBuffer();
                if (choicePanel.text.getText().trim().equals(""))
                    errormsg.append("You have not specified anything for text.\n");
                if (choicePanel.variable.isVisible() && choicePanel.variable.getText().trim().equals(""))
                    errormsg.append("You have not specified anything for the variable field.\n");
                if (choicePanel.iftrue.getText().trim().equals(""))
                    errormsg.append("You have not specified anything for the \"Value if Selected\" field.\n");
                if (choicePanel.iffalse.isVisible() && choicePanel.iffalse.getText().trim().equals(""))
                    errormsg.append("You have not specified anything for the \"Value if not Selected\" field.\n");
                if (errormsg.length() != 0) {
                    String msg = errormsg.substring(0, errormsg.length() - 1);
                    JOptionPane.showMessageDialog(RunnerClass.mf, msg, "Incomplete Data", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                Choice c;
                //Checks if it is editing or not to see whether to create a Choice object or to get one from the JList
                if (isEditing)
                    //Gets the elemnet from the appropriate JList
                    if (choiceListPanel1.isVisible())
                        c = (Choice) choices.getElement();
                    else
                        c = (Choice) choices2.getElement();
                else
                    c = new Choice();
                c.text = choicePanel.text.getText().trim();
                //Sets the values
                if (choicePanel.variable.isVisible()) {
                    c.variable = choicePanel.variable.getText().trim();
                    c.trueIf = choicePanel.iftrue.getText().trim();
                    c.falseIf = choicePanel.iffalse.getText().trim();
                    c.set = choicePanel.preselected.isSelected();
                } else
                    c.value = choicePanel.iftrue.getText().trim();
                //If it is not editing the choice is added to the appropriate JList
                if (!isEditing)
                    if (choiceListPanel1.isVisible()) {
                        choices.add(c);
                        preselected.addItem(c);
                    } else
                        choices2.add(c);

                RunnerClass.mf.removeP();
            }
        });
        RunnerClass.mf.addP(choicePanel);
        RunnerClass.mf.pack();
    }//GEN-LAST:event_addActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        //Performs appropriate action when editing an made element
        isEditing = true;
        addActionPerformed(null);
    }//GEN-LAST:event_editActionPerformed

    private void removeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeActionPerformed
        //Removes current element
        if (choiceListPanel1.isVisible()) {
            System.out.println(choices.getElement());
            preselected.removeItem(choices.getElement());
            choices.remove();
        } else
            choices2.remove();
    }//GEN-LAST:event_removeActionPerformed

    private void upActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upActionPerformed
        //Moves up current element one index
        if (choiceListPanel1.isVisible())
            choices.moveUp();
        else
            choices2.moveUp();
    }//GEN-LAST:event_upActionPerformed

    private void downActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downActionPerformed
        //Moves down current element one index
        if (choiceListPanel1.isVisible())
            choices.moveDown();
        else
            choices2.moveDown();
    }//GEN-LAST:event_downActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    public javax.swing.JComboBox align;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    public javax.swing.JRadioButton checkBox;
    public javax.swing.JPanel choiceListPanel1;
    public javax.swing.JPanel choiceListPanel2;
    public javax.swing.JList choicesList;
    public javax.swing.JList choicesList2;
    public javax.swing.JRadioButton comboBox;
    public javax.swing.JTextField comboBoxLabel;
    public javax.swing.JTextField description;
    public javax.swing.JCheckBox descriptionOption;
    private javax.swing.JPanel descriptionPanel;
    private javax.swing.JButton down;
    private javax.swing.JButton edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JPanel okPanel3;
    public javax.swing.JComboBox preselected;
    public javax.swing.JRadioButton radioButton;
    private javax.swing.JButton remove;
    private javax.swing.JButton up;
    public javax.swing.JTextField variable;
    public javax.swing.JPanel variablePanel;
    // End of variables declaration//GEN-END:variables
}
