/*
 * PackJacket - GUI frontend to IzPack to make Java-based installers
 * Copyright (C) 2008 - 2009  Amandeep Grewal, Manodasan Wignarajah
 *
 * PackJacket is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PackJacket is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PackJacket.  If not, see <http://www.gnu.org/licenses/>.
 */
package packjacket.gui;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import packjacket.RunnerClass;
import packjacket.gui.advancedgui.LafPanel;
import packjacket.xml.Laf;

/**
 * An advanced gui panel for such things as header, progress bar, LaFs
 * @author Manodasan Wignarajah
 * @author Amandeep Grewal
 */
public class AdvancedGUIPanel extends javax.swing.JPanel {

    public ArrayListModel<Laf> lafs;
    public boolean isEditing;

    /** Creates new form AdvancedGUI */
    public AdvancedGUIPanel() {
        initComponents();
        lafs = new ArrayListModel(lookAndFeelList);
        isEditing = false;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        upBtn = new javax.swing.JButton();
        downBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lookAndFeelList = new javax.swing.JList();
        headerOption = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        headingImage = new javax.swing.JTextField();
        browseBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        headingImagePosition = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        headerBackgroundSelect = new javax.swing.JButton();
        fontColourSelect = new javax.swing.JButton();
        counterOption = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        counterPosition = new javax.swing.JComboBox();
        counterType = new javax.swing.JComboBox();
        fontMultiplier = new javax.swing.JSpinner(new javax.swing.SpinnerNumberModel(0,0,2147483647,1));
        jButton1 = new javax.swing.JButton();
        backgroundColour = new javax.swing.JLabel();
        fontColour = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Look and Feel"));

        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/edit.png"))); // NOI18N
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        upBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/up.png"))); // NOI18N
        upBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upBtnActionPerformed(evt);
            }
        });

        downBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/down.png"))); // NOI18N
        downBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downBtnActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(lookAndFeelList);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(downBtn)
                    .addComponent(upBtn)
                    .addComponent(deleteBtn)
                    .addComponent(editBtn)
                    .addComponent(addBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        headerOption.setText("Header on Each Panel");
        headerOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headerOptionActionPerformed(evt);
            }
        });

        jLabel1.setText("Heading Image");
        jLabel1.setEnabled(false);

        headingImage.setEditable(false);
        headingImage.setEnabled(false);

        browseBtn.setText("Browse");
        browseBtn.setEnabled(false);
        browseBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                browseBtnActionPerformed(evt);
            }
        });

        jLabel2.setText("Heading Image Position");
        jLabel2.setEnabled(false);

        headingImagePosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Right", "Left" }));
        headingImagePosition.setEnabled(false);

        jLabel3.setText("Font Multiplier");
        jLabel3.setEnabled(false);

        jLabel4.setText("Heading Background Colour");
        jLabel4.setEnabled(false);

        jLabel5.setText("Heading Font Colour");
        jLabel5.setEnabled(false);

        headerBackgroundSelect.setText("Select Colour");
        headerBackgroundSelect.setEnabled(false);
        headerBackgroundSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                headerBackgroundSelectActionPerformed(evt);
            }
        });

        fontColourSelect.setText("Select Colour");
        fontColourSelect.setEnabled(false);
        fontColourSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fontColourSelectActionPerformed(evt);
            }
        });

        counterOption.setText("Show Step Counter");
        counterOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                counterOptionActionPerformed(evt);
            }
        });

        jLabel6.setText("Counter Type");
        jLabel6.setEnabled(false);

        jLabel7.setText("Counter Position");
        jLabel7.setEnabled(false);

        counterPosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "In Navigation Bar", "In Header" }));
        counterPosition.setEnabled(false);

        counterType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Text", "Progress Bar" }));
        counterType.setEnabled(false);

        fontMultiplier.setEnabled(false);
        fontMultiplier.setValue(new Integer(2));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/ok.png"))); // NOI18N
        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        backgroundColour.setBackground(new java.awt.Color(254, 254, 254));
        backgroundColour.setOpaque(true);

        fontColour.setBackground(new java.awt.Color(1, 1, 1));
        fontColour.setOpaque(true);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(headerOption)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(counterOption)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel5))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(backgroundColour, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(fontMultiplier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(headingImagePosition, javax.swing.GroupLayout.Alignment.LEADING, 0, 138, Short.MAX_VALUE)
                                    .addComponent(headingImage, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(counterPosition, javax.swing.GroupLayout.Alignment.LEADING, 0, 138, Short.MAX_VALUE)
                                    .addComponent(counterType, javax.swing.GroupLayout.Alignment.LEADING, 0, 138, Short.MAX_VALUE)
                                    .addComponent(fontColour, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(browseBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(headerBackgroundSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fontColourSelect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(headerOption)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(headingImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(browseBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(headingImagePosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(fontMultiplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(headerBackgroundSelect)
                            .addComponent(backgroundColour, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(fontColourSelect))
                                .addGap(18, 18, 18)
                                .addComponent(counterOption))
                            .addComponent(fontColour, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(counterType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(counterPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(1, 1, 1)
                .addComponent(jButton1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sets some UI fields from values from an data fields
     */
    public void adjustGUI() {
        headerOptionActionPerformed(null);
        counterOptionActionPerformed(null);
    }
    private void headerOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headerOptionActionPerformed
        //Enables fields depending on if the header option is selected
        browseBtn.setEnabled(headerOption.isSelected());
        headingImagePosition.setEnabled(headerOption.isSelected());
        fontMultiplier.setEnabled(headerOption.isSelected());
        fontColourSelect.setEnabled(headerOption.isSelected());
        headerBackgroundSelect.setEnabled(headerOption.isSelected());
        headingImage.setEnabled(headerOption.isSelected());
        headingImage.setBackground(headerOption.isSelected() ? new Color(254, 254, 254) : new Color(229, 229, 229));
        jLabel1.setEnabled(headerOption.isSelected());
        jLabel2.setEnabled(headerOption.isSelected());
        jLabel3.setEnabled(headerOption.isSelected());
        jLabel4.setEnabled(headerOption.isSelected());
        jLabel5.setEnabled(headerOption.isSelected());
    }//GEN-LAST:event_headerOptionActionPerformed

    private void counterOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_counterOptionActionPerformed
        //Enables fields depending on if counter option is selected
        counterType.setEnabled(counterOption.isSelected());
        counterPosition.setEnabled(counterOption.isSelected());
        jLabel6.setEnabled(counterOption.isSelected());
        jLabel7.setEnabled(counterOption.isSelected());
    }//GEN-LAST:event_counterOptionActionPerformed

    private void fontColourSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fontColourSelectActionPerformed
        //Sets colour from user input
        Color colour = JColorChooser.showDialog(null, "Foreground Colour", Color.white);
        if (colour != null)
            fontColour.setBackground(colour);
    }//GEN-LAST:event_fontColourSelectActionPerformed

    private void headerBackgroundSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_headerBackgroundSelectActionPerformed
        //Sets colour from user input
        Color colour = JColorChooser.showDialog(null, "Background Colour", Color.white);
        if (colour != null)
            backgroundColour.setBackground(colour);
    }//GEN-LAST:event_headerBackgroundSelectActionPerformed

    private void browseBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_browseBtnActionPerformed
        GUIUtils.open("images", headingImage);
    }//GEN-LAST:event_browseBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        //Performs the action to do when user clicks to add an LAF
        isEditing = false;
        final LafPanel lafPanel = new LafPanel();
        makePanel(lafPanel);
    }//GEN-LAST:event_addBtnActionPerformed

    /**
     * Creates the panel which allows the user to specify options for the chosen LAF
     * @param laf The panel which contains the fields for getting input from user for LAF
     */
    private void makePanel(final LafPanel laf) {
        ((BtnPanel) laf.okPanel).addOkBtnActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {
                //Shows error message
                StringBuffer errormsg = new StringBuffer();
                errormsg.append(((OSPanel) laf.osPanel).getError());
                if (errormsg.length() != 0) {
                    String msg = errormsg.substring(0, errormsg.length() - 1);
                    JOptionPane.showMessageDialog(RunnerClass.mf, msg, "Incomplete Data", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                //Creates or gets the Laf database object depending on whether the user is editing or adding a new LAF
                Laf l;
                if (isEditing)
                    l = lafs.getElement();
                else
                    l = new Laf();
                //Stores the values in the database
                l.guiprefs_laf_name = laf.lookAndFeel.getSelectedItem().toString();
                l.guiprefs_laf_liquid_decorate_dialogs = laf.dialogsLiquid.isSelected();
                l.guiprefs_laf_liquid_decorate_frames = laf.framesLiquid.isSelected();
                l.guiprefs_laf_looks_variant = laf.jgoodiesVariant.getSelectedItem().toString();
                l.guiprefs_laf_substance_variant = laf.substanceVariant.getSelectedItem().toString();
                l.guiprefs_laf_os = ((OSPanel) laf.osPanel).getOS();

                //Adds the laf if the user isn't editing an already created laf
                if (!isEditing)
                    lafs.add(l);

                //Removes the laf panel
                RunnerClass.mf.removeP();
            }
        });
        RunnerClass.mf.addP(laf);
        laf.lookAndFeelActionPerformed();
    }
    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        //Sets up the panel with the info they specified for the laf the user is editing
        isEditing = true;
        final LafPanel laf = new LafPanel();
        Laf l = lafs.getElement();
        laf.lookAndFeel.setSelectedItem(l.guiprefs_laf_name);
        laf.dialogsLiquid.setSelected(l.guiprefs_laf_liquid_decorate_dialogs);
        laf.framesLiquid.setSelected(l.guiprefs_laf_liquid_decorate_frames);
        laf.jgoodiesVariant.setSelectedItem(l.guiprefs_laf_looks_variant);
        laf.substanceVariant.setSelectedItem(l.guiprefs_laf_substance_variant);
        ((OSPanel) laf.osPanel).setOS(l.guiprefs_laf_os);

        makePanel(laf);
    }//GEN-LAST:event_editBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        //Removes the currently chosen laf from the list
        lafs.remove();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void upBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upBtnActionPerformed
        //Moves the currently chosen laf up one index on the list
        lafs.moveUp();
    }//GEN-LAST:event_upBtnActionPerformed

    private void downBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downBtnActionPerformed
        //Moves the currently chosen laf down on index on the listF
        lafs.moveDown();
    }//GEN-LAST:event_downBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Removes the panel
        RunnerClass.mf.removeP();
    }//GEN-LAST:event_jButton1ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addBtn;
    public javax.swing.JLabel backgroundColour;
    public javax.swing.JButton browseBtn;
    public javax.swing.JCheckBox counterOption;
    public javax.swing.JComboBox counterPosition;
    public javax.swing.JComboBox counterType;
    public javax.swing.JButton deleteBtn;
    public javax.swing.JButton downBtn;
    public javax.swing.JButton editBtn;
    public javax.swing.JLabel fontColour;
    public javax.swing.JButton fontColourSelect;
    public javax.swing.JSpinner fontMultiplier;
    public javax.swing.JButton headerBackgroundSelect;
    public javax.swing.JCheckBox headerOption;
    public javax.swing.JTextField headingImage;
    public javax.swing.JComboBox headingImagePosition;
    public javax.swing.JButton jButton1;
    public javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JList lookAndFeelList;
    public javax.swing.JButton upBtn;
    // End of variables declaration//GEN-END:variables
}
