/*
 * PackJacket - GUI frontend to IzPack to make Java-based installers
 * Copyright (C) 2008 - 2009  Amandeep Grewal, Manodasan Wignarajah
 *
 * PackJacket is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PackJacket is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PackJacket.  If not, see <http://www.gnu.org/licenses/>.
 */
package packjacket.gui;

import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 * GeneralShortcutsPanel
 * @author Manodasan Wignarajah
 */
public class GeneralShortcutsPanel extends javax.swing.JPanel {

    /** Creates new form GeneralShortcutsPanel */
    public GeneralShortcutsPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        targetFileOption = new javax.swing.JCheckBox();
        urlOption = new javax.swing.JCheckBox();
        url = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        programGroup = new javax.swing.JCheckBox();
        desktop = new javax.swing.JCheckBox();
        startup = new javax.swing.JCheckBox();
        applications = new javax.swing.JCheckBox();
        startMenu = new javax.swing.JCheckBox();
        targetFile = new javax.swing.JComboBox();

        jButton1.setText("jButton1");

        jLabel1.setText("Name");

        targetFileOption.setSelected(true);
        targetFileOption.setText("Target File");
        targetFileOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                targetFileOptionActionPerformed(evt);
            }
        });

        urlOption.setText("URL (Unix Only)");
        urlOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urlOptionActionPerformed(evt);
            }
        });

        url.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Place in ..."));

        programGroup.setText("Program Group");

        desktop.setText("Desktop");

        startup.setText("Startup");

        applications.setText("Applications");

        startMenu.setText("Start Menu");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(programGroup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(desktop)
                        .addGap(18, 18, 18)
                        .addComponent(startup))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(applications)
                        .addGap(18, 18, 18)
                        .addComponent(startMenu)))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(programGroup)
                    .addComponent(desktop)
                    .addComponent(startup))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(applications)
                    .addComponent(startMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        targetFile.setEditable(true);
        targetFile.setModel(GUIUtils.getAllFilesForComboBoxModel(false));
        AutoCompleteDecorator.decorate(targetFile);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(targetFileOption)
                            .addComponent(urlOption))
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(targetFile, 0, 152, Short.MAX_VALUE)
                            .addComponent(url, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE)
                            .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, 152, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(targetFileOption)
                    .addComponent(targetFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urlOption)
                    .addComponent(url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sets the GUI fields as enabled or disabled depending on what is selected
     */
    public void adjustFields() {
        urlOptionActionPerformed(null);
        targetFileOptionActionPerformed(null);
    }
    private void urlOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urlOptionActionPerformed
        //Enables url stuff depending on if URl is selected
        if (urlOption.isSelected()) {
            url.setEnabled(true);
            targetFile.setEnabled(false);
            targetFileOption.setSelected(false);
        } else {
            url.setEnabled(false);
            targetFileOption.setSelected(true);
            targetFile.setEnabled(true);
        }
    }//GEN-LAST:event_urlOptionActionPerformed

    private void targetFileOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_targetFileOptionActionPerformed
        //Enables the targetFile stuff depending on whether it is selected
        if (targetFileOption.isSelected()) {
            targetFile.setEnabled(true);
            url.setEnabled(false);
            urlOption.setSelected(false);
        } else {
            targetFile.setEnabled(false);
            urlOption.setSelected(true);
            url.setEnabled(true);
        }
    }//GEN-LAST:event_targetFileOptionActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox applications;
    public javax.swing.JCheckBox desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JTextField name;
    public javax.swing.JCheckBox programGroup;
    public javax.swing.JCheckBox startMenu;
    public javax.swing.JCheckBox startup;
    public javax.swing.JComboBox targetFile;
    public javax.swing.JCheckBox targetFileOption;
    public javax.swing.JTextField url;
    public javax.swing.JCheckBox urlOption;
    // End of variables declaration//GEN-END:variables
}
