/*
 * PackJacket - GUI frontend to IzPack to make Java-based installers
 * Copyright (C) 2008 - 2009  Amandeep Grewal, Manodasan Wignarajah
 *
 * PackJacket is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PackJacket is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PackJacket.  If not, see <http://www.gnu.org/licenses/>.
 */
package packjacket.gui;

import java.util.Arrays;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;
import packjacket.RunnerClass;

/**
 * Select languages for installer
 * @author Amandeep Grewal
 * @author Manodasan Wignarajah
 */
public class LanguagePanel extends javax.swing.JPanel {

    public ArrayListModel<String> langs;

    /** Creates new form LanguagePanel */
    public LanguagePanel() {
        initComponents();

        langs = new ArrayListModel<String>(langsList);
        langs.add("English");
        langsSelect.removeItem("English");
        langsSelect.setSelectedItem("");
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LangLabel = new javax.swing.JLabel();
        addLocaleButton = new javax.swing.JButton();
        deleteLocaleButton = new javax.swing.JButton();
        upLocaleButton = new javax.swing.JButton();
        downLocaleButton = new javax.swing.JButton();
        lastListScroll = new javax.swing.JScrollPane();
        langsList = new javax.swing.JList();
        langsSelect = new javax.swing.JComboBox();
        useFlags = new javax.swing.JCheckBox();
        langDisplayType = new javax.swing.JComboBox();
        langDisplayTypeLabel = new javax.swing.JLabel();

        LangLabel.setText("Name");

        addLocaleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/add.png"))); // NOI18N
        addLocaleButton.setToolTipText("Add");
        addLocaleButton.setPreferredSize(new java.awt.Dimension(35, 25));
        addLocaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLocaleButtonActionPerformed(evt);
            }
        });

        deleteLocaleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/remove.png"))); // NOI18N
        deleteLocaleButton.setToolTipText("Remove");
        deleteLocaleButton.setPreferredSize(new java.awt.Dimension(35, 25));
        deleteLocaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteLocaleButtonActionPerformed(evt);
            }
        });

        upLocaleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/up.png"))); // NOI18N
        upLocaleButton.setToolTipText("Move up");
        upLocaleButton.setPreferredSize(new java.awt.Dimension(35, 25));
        upLocaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upLocaleButtonActionPerformed(evt);
            }
        });

        downLocaleButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/down.png"))); // NOI18N
        downLocaleButton.setToolTipText("Move down");
        downLocaleButton.setPreferredSize(new java.awt.Dimension(35, 25));
        downLocaleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downLocaleButtonActionPerformed(evt);
            }
        });

        langsList.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                langsListKeyPressed(evt);
            }
        });
        lastListScroll.setViewportView(langsList);

        langsSelect.setEditable(true);
        langsSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Catalunyan", "Chinese (Simplified)", "Chinese (Traditional)", "Czech", "Danish", "Dutch", "English", "Finnish", "French", "Galician", "German", "Greek", "Hungarian", "Indonesian", "Italian", "Japanese", "Korean", "Malaysian", "Nederlands", "Norwegian", "Persian", "Polish", "Portuguese (Brazilian)", "Romanian", "Russian", "Serbian", "Slovakian", "Spanish", "Swedish", "Turkish", "Ukrainian" }));
        AutoCompleteDecorator.decorate(langsSelect);
        langsSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                langsSelectActionPerformed(evt);
            }
        });

        useFlags.setSelected(true);
        useFlags.setText("Use Flags");

        langDisplayType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Default", "Native", "ISO3" }));

        langDisplayTypeLabel.setText("Language Display Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lastListScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(langDisplayTypeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(langDisplayType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(useFlags)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LangLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(langsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addLocaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(deleteLocaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(upLocaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(downLocaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(langsSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LangLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addLocaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteLocaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upLocaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(downLocaleButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastListScroll, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(useFlags)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(langDisplayType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(langDisplayTypeLabel))))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addLocaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLocaleButtonActionPerformed
        //Stores the value being searched for
        String target = langsSelect.getSelectedItem().toString().trim();
        //Shows error, if there are no items to add
        if (langsSelect.getItemCount() == 0) {
            JOptionPane.showMessageDialog(RunnerClass.mf, "You have already added all possible languages!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Shows error, if already added
        if (langs.list.contains(target)) {
            JOptionPane.showMessageDialog(RunnerClass.mf, "You have already listed that language!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Sets the trimmed version of the text in the combo box
        langsSelect.setSelectedItem(target);
        //Gives error message if not in combo box model
        if (langsSelect.getSelectedIndex() == -1 || !langsSelect.getItemAt(langsSelect.getSelectedIndex()).equals(target)) {
            JOptionPane.showMessageDialog(RunnerClass.mf, "The language you entered is not recognized!", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Adds language to list
        langs.add(target);
        //Removes langauge from languages to add list
        langsSelect.removeItemAt(langsSelect.getSelectedIndex());
    }//GEN-LAST:event_addLocaleButtonActionPerformed

    private void deleteLocaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteLocaleButtonActionPerformed
        //Stores previously selected item
        String current = langsSelect.getSelectedItem().toString();
        //Adds language back to the list with possible languages to add
        langsSelect.addItem(langs.getElement());
        //Gets the model of the combobox
        ComboBoxModel model = langsSelect.getModel();
        //Creates an array and stores all elements of model in it
        String[] items = new String[model.getSize()];
        for (int a = 0; a < items.length; a++)
            items[a] = model.getElementAt(a).toString();
        //Sorts the array
        Arrays.sort(items);
        //Sets the array as the new model
        langsSelect.setModel(new DefaultComboBoxModel(items));
        //Sets previously selected item
        langsSelect.setSelectedItem(current);
        //Removes the currently chosen language
        langs.remove();
    }//GEN-LAST:event_deleteLocaleButtonActionPerformed

    private void upLocaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upLocaleButtonActionPerformed
        //Moves the currently chosen language element one index up
        langs.moveUp();
    }//GEN-LAST:event_upLocaleButtonActionPerformed

    private void downLocaleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downLocaleButtonActionPerformed
        //Moves the currently chosen language element one index down
        langs.moveDown();
    }//GEN-LAST:event_downLocaleButtonActionPerformed

    private void langsSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_langsSelectActionPerformed
        //If the user presses enter, the entered language is added if it is recognized
        if (evt.getActionCommand().equals("comboBoxEdited"))
            addLocaleButtonActionPerformed(null);
    }//GEN-LAST:event_langsSelectActionPerformed

    private void langsListKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_langsListKeyPressed
        //If delete button on keyboard is pressed, delete it
        if (evt.getKeyCode() == 127)
            deleteLocaleButtonActionPerformed(null);
    }//GEN-LAST:event_langsListKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LangLabel;
    private javax.swing.JButton addLocaleButton;
    private javax.swing.JButton deleteLocaleButton;
    private javax.swing.JButton downLocaleButton;
    public javax.swing.JComboBox langDisplayType;
    private javax.swing.JLabel langDisplayTypeLabel;
    private javax.swing.JList langsList;
    private javax.swing.JComboBox langsSelect;
    private javax.swing.JScrollPane lastListScroll;
    private javax.swing.JButton upLocaleButton;
    public javax.swing.JCheckBox useFlags;
    // End of variables declaration//GEN-END:variables
}
