/*
 * PackJacket - GUI frontend to IzPack to make Java-based installers
 * Copyright (C) 2008 - 2009  Amandeep Grewal, Manodasan Wignarajah
 *
 * PackJacket is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * PackJacket is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with PackJacket.  If not, see <http://www.gnu.org/licenses/>.
 */
package packjacket.gui.advancedgui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import packjacket.RunnerClass;
import packjacket.gui.BtnPanel;
import packjacket.gui.OSPanel;

/**
 * Contains implementation for the Laf Panel
 * @author Manodasan Wignarajah
 */
public class LafPanel extends javax.swing.JPanel {

    /** Creates new form LafPanel */
    public LafPanel() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lookAndFeel = new javax.swing.JComboBox();
        osPanel = new javax.swing.JPanel();
        lookFeelPanel = new javax.swing.JPanel();
        framesLiquid = new javax.swing.JCheckBox();
        dialogsLiquid = new javax.swing.JCheckBox();
        jgoodiesVariantLabel = new javax.swing.JLabel();
        jgoodiesVariant = new javax.swing.JComboBox();
        substanceVariantLabel = new javax.swing.JLabel();
        substanceVariant = new javax.swing.JComboBox();
        okPanel = new javax.swing.JPanel();

        jLabel1.setText("Look and Feel");

        lookAndFeel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kunststoff", "Liquid", "Metouia", "JGoodies Looks", "Substance" }));
        lookAndFeel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookAndFeelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout osPanelLayout = new javax.swing.GroupLayout(osPanel);
        osPanel.setLayout(osPanelLayout);
        osPanelLayout.setHorizontalGroup(
            osPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 172, Short.MAX_VALUE)
        );
        osPanelLayout.setVerticalGroup(
            osPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 173, Short.MAX_VALUE)
        );

        osPanel = new OSPanel();

        framesLiquid.setText("Frames in Liquid Style");
        framesLiquid.setVisible(false);

        dialogsLiquid.setText("Dialogs in Liquid Style");
        dialogsLiquid.setVisible(false);

        jgoodiesVariantLabel.setText("JGoodies Variant");
        jgoodiesVariantLabel.setVisible(false);

        jgoodiesVariant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Windows", "Plastic", "PlasticXP", "Plastic3D" }));
        jgoodiesVariant.setVisible(false);

        substanceVariantLabel.setText("Substance Variant");
        substanceVariantLabel.setVisible(false);

        substanceVariant.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Business", "Business-blue", "Business-black", "Creme", "Sahara", "Moderate", "Officesilver" }));
        substanceVariant.setVisible(false);

        javax.swing.GroupLayout lookFeelPanelLayout = new javax.swing.GroupLayout(lookFeelPanel);
        lookFeelPanel.setLayout(lookFeelPanelLayout);
        lookFeelPanelLayout.setHorizontalGroup(
            lookFeelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookFeelPanelLayout.createSequentialGroup()
                .addGroup(lookFeelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lookFeelPanelLayout.createSequentialGroup()
                        .addComponent(substanceVariantLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(substanceVariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(framesLiquid)
                    .addComponent(dialogsLiquid)
                    .addGroup(lookFeelPanelLayout.createSequentialGroup()
                        .addComponent(jgoodiesVariantLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jgoodiesVariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        lookFeelPanelLayout.setVerticalGroup(
            lookFeelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lookFeelPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(framesLiquid)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dialogsLiquid)
                .addGap(6, 6, 6)
                .addGroup(lookFeelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jgoodiesVariantLabel)
                    .addComponent(jgoodiesVariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(lookFeelPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(substanceVariant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(substanceVariantLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout okPanelLayout = new javax.swing.GroupLayout(okPanel);
        okPanel.setLayout(okPanelLayout);
        okPanelLayout.setHorizontalGroup(
            okPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 162, Short.MAX_VALUE)
        );
        okPanelLayout.setVerticalGroup(
            okPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 34, Short.MAX_VALUE)
        );

        okPanel = new BtnPanel(new ActionListener() {

            public void actionPerformed(ActionEvent e) {
                
                RunnerClass.mf.removeP();
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lookFeelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(osPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addComponent(okPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lookAndFeel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lookFeelPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(osPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(okPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lookAndFeelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookAndFeelActionPerformed
        //Sets the fields visible or not depending on what's chosen
        framesLiquid.setVisible(lookAndFeel.getSelectedItem().equals("Liquid"));
        dialogsLiquid.setVisible(lookAndFeel.getSelectedItem().equals("Liquid"));
        jgoodiesVariantLabel.setVisible(lookAndFeel.getSelectedItem().equals("JGoodies Looks"));
        jgoodiesVariant.setVisible(lookAndFeel.getSelectedItem().equals("JGoodies Looks"));
        substanceVariantLabel.setVisible(lookAndFeel.getSelectedItem().equals("Substance"));
        substanceVariant.setVisible(lookAndFeel.getSelectedItem().equals("Substance"));
        RunnerClass.mf.pack();
    }//GEN-LAST:event_lookAndFeelActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JCheckBox dialogsLiquid;
    public javax.swing.JCheckBox framesLiquid;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JComboBox jgoodiesVariant;
    private javax.swing.JLabel jgoodiesVariantLabel;
    public javax.swing.JComboBox lookAndFeel;
    private javax.swing.JPanel lookFeelPanel;
    public javax.swing.JPanel okPanel;
    public javax.swing.JPanel osPanel;
    public javax.swing.JComboBox substanceVariant;
    private javax.swing.JLabel substanceVariantLabel;
    // End of variables declaration//GEN-END:variables

    public void lookAndFeelActionPerformed() {
        lookAndFeelActionPerformed(null);
    }
}
